Imported Upstream version 0.0.21

diff --git a/gst/fsrtpconference/Makefile.in b/gst/fsrtpconference/Makefile.in
--- a/gst/fsrtpconference/Makefile.in
+++ b/gst/fsrtpconference/Makefile.in
@@ -20,7 +20,8 @@
 
 #glib_enum_headers=$(colorbalance_headers)
 #glib_enum_define=GST_COLOR_BALANCE
-#glib_enum_prefix=gst_color_balance
+#glib_gen_prefix=gst_color_balance
+#glib_gen_basename=colorbalance
 
 
 VPATH = @srcdir@
@@ -47,8 +48,7 @@ host_triplet = @host@
 @ENABLE_GTK_DOC_TRUE@am__append_1 = libfsrtpconference_doc.la
 @ENABLE_GTK_DOC_TRUE@am__append_2 = fs-rtp-conference-plugin.doc.c
 DIST_COMMON = $(noinst_HEADERS) $(srcdir)/Makefile.am \
-	$(srcdir)/Makefile.in \
-	$(top_srcdir)/common-modified/glib-gen.mak
+	$(srcdir)/Makefile.in $(top_srcdir)/common/gst-glib-gen.mak
 subdir = gst/fsrtpconference
 ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
 am__aclocal_m4_deps = $(top_srcdir)/common/m4/as-ac-expand.m4 \
@@ -433,14 +433,15 @@ libfsrtpconference_la_LDFLAGS = $(GST_PLUGIN_LDFLAGS)
 
 @ENABLE_GTK_DOC_TRUE@libfsrtpconference_doc_la_LIBADD = $(libfsrtpconference_la_LIBADD)
 glib_enum_define = FS_RTP
-glib_enum_prefix = _fs_rtp
+glib_gen_prefix = _fs_rtp
+glib_gen_basename = fs-rtp
 enum_headers = $(foreach h,$(glib_enum_headers),\n\#include \"$(h)\")
 all: $(BUILT_SOURCES)
 	$(MAKE) $(AM_MAKEFLAGS) all-am
 
 .SUFFIXES:
 .SUFFIXES: .c .lo .o .obj
-$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am $(top_srcdir)/common-modified/glib-gen.mak $(am__configure_deps)
+$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am $(top_srcdir)/common/gst-glib-gen.mak $(am__configure_deps)
 	@for dep in $?; do \
 	  case '$(am__configure_deps)' in \
 	    *$$dep*) \
@@ -777,16 +778,16 @@ uninstall-am: uninstall-pluginLTLIBRARIES
 
 
 @ENABLE_GTK_DOC_TRUE@%.doc.c: %.c
-@ENABLE_GTK_DOC_TRUE@	sed -e 's:GST_PLUGIN_DEFINE:GST_PLUGIN_DEFINE_STATIC:' $< > $@
+@ENABLE_GTK_DOC_TRUE@	$(AM_V_GEN)sed -e 's:GST_PLUGIN_DEFINE:GST_PLUGIN_DEFINE_STATIC:' $< > $@
 
 # Build the build sources
 
 fs-rtp-marshal.list: $(libfsrtpconference_convenience_la_SOURCES) Makefile.am
-	( cd $(srcdir) && \
+	$(AM_V_GEN)( cd $(srcdir) && \
 	sed -n -e 's/.*fs_rtp_marshal_\([[:upper:][:digit:]]*__[[:upper:][:digit:]_]*\).*/\1/p' \
 	$(libfsrtpconference_convenience_la_SOURCES) ) \
 	| sed -e 's/__/:/' -e 'y/_/,/' | sort -u > $@.tmp
-	if cmp -s $@.tmp $@; then \
+	@if cmp -s $@.tmp $@; then \
 		rm $@.tmp; \
 		touch $@; \
 	else \
@@ -794,27 +795,27 @@ fs-rtp-marshal.list: $(libfsrtpconference_convenience_la_SOURCES) Makefile.am
 	fi
 
 # these are all the rules generating the relevant files
-%-marshal.h: %-marshal.list Makefile
-	glib-genmarshal --header --prefix=$(glib_enum_prefix)_marshal $< > $*-marshal.h.tmp
-	mv $*-marshal.h.tmp $*-marshal.h
+$(glib_gen_basename)-marshal.h: $(glib_gen_basename)-marshal.list
+	$(AM_V_GEN)glib-genmarshal --header --prefix=$(glib_gen_prefix)_marshal $^ > $(glib_gen_basename)-marshal.h.tmp && \
+	mv $(glib_gen_basename)-marshal.h.tmp $(glib_gen_basename)-marshal.h
 
-%-marshal.c: %-marshal.list Makefile
-	echo "#include \"$*-marshal.h\"" >> $*-marshal.c.tmp
-	glib-genmarshal --body --prefix=$(glib_enum_prefix)_marshal $< >> $*-marshal.c.tmp
-	mv $*-marshal.c.tmp $*-marshal.c
+$(glib_gen_basename)-marshal.c: $(glib_gen_basename)-marshal.list
+	$(AM_V_GEN)echo "#include \"$(glib_gen_basename)-marshal.h\"" >> $(glib_gen_basename)-marshal.c.tmp && \
+	glib-genmarshal --body --prefix=$(glib_gen_prefix)_marshal $^ >> $(glib_gen_basename)-marshal.c.tmp && \
+	mv $(glib_gen_basename)-marshal.c.tmp $(glib_gen_basename)-marshal.c
 
-%-enum-types.h: $(glib_enum_headers) Makefile
-	glib-mkenums \
+$(glib_gen_basename)-enumtypes.h: $(glib_enum_headers)
+	$(AM_V_GEN)glib-mkenums \
 	--fhead "#ifndef __$(glib_enum_define)_ENUM_TYPES_H__\n#define __$(glib_enum_define)_ENUM_TYPES_H__\n\n#include <glib-object.h>\n\nG_BEGIN_DECLS\n" \
 	--fprod "\n/* enumerations from \"@filename@\" */\n" \
-	--vhead "GType @enum_name@_get_type (void);\n#define $(glib_enum_define)_TYPE_@ENUMSHORT@ (@enum_name@_get_type())\n"         \
+	--vhead "GType @enum_name@_get_type (void);\n#define GST_TYPE_@ENUMSHORT@ (@enum_name@_get_type())\n"         \
 	--ftail "G_END_DECLS\n\n#endif /* __$(glib_enum_define)_ENUM_TYPES_H__ */" \
 	$^ > $@
 
-%-enum-types.c: $(glib_enum_headers) Makefile
-	@if test "x$(glib_enum_headers)" = "x"; then echo "ERROR: glib_enum_headers is empty, please fix Makefile"; exit 1; fi
-	glib-mkenums \
-	--fhead "#include \"$*-enum-types.h\"\n$(enum_headers)" \
+$(glib_gen_basename)-enumtypes.c: $(glib_enum_headers)
+	@if test "x$(glib_enum_headers)" == "x"; then echo "ERROR: glib_enum_headers is empty, please fix Makefile"; exit 1; fi
+	$(AM_V_GEN)glib-mkenums \
+	--fhead "#include \"$(glib_gen_basename)-enumtypes.h\"\n$(enum_headers)" \
 	--fprod "\n/* enumerations from \"@filename@\" */" \
 	--vhead "GType\n@enum_name@_get_type (void)\n{\n  static volatile gsize g_define_type_id__volatile = 0;\n  if (g_once_init_enter (&g_define_type_id__volatile)) {\n    static const G@Type@Value values[] = {"     \
 	--vprod "      { @VALUENAME@, \"@VALUENAME@\", \"@valuenick@\" }," \
@@ -824,10 +825,10 @@ fs-rtp-marshal.list: $(libfsrtpconference_convenience_la_SOURCES) Makefile.am
 # a hack rule to make sure .Plo files exist because they get include'd
 # from Makefile's
 .deps/%-marshal.Plo:
-	touch $@
+	@touch $@
 
-.deps/%-enum-types.Plo:
-	touch $@
+.deps/%-enumtypes.Plo:
+	@touch $@
 
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
